export const GET_MOVIES = "GET_MOVIES";
export const LOAD_MOVIE_SUCCESS = "LOAD_MOVIE_SUCCESS";
export const MOVIE_HAS_ERRORED = "MOVIE_HAS_ERRORED";
export const MOVIE_IS_LOADING = "MOVIE_IS_LOADING";
export const LOAD_SIM_MOVIE_SUCCESS = "LOAD_SIM_MOVIE_SUCCESS";
export const MOVIE_SIM_HAS_ERRORED = "MOVIE_SIM_HAS_ERRORED";
export const MOVIE_SIM_IS_LOADING = "MOVIE_SIM_IS_LOADING";
